packages: []
catalogs:
  build:
    tsdown: ^0.20.3
  dev:
    bumpp: ^10.4.1
    pncat: ^0.10.4
    simple-git-hooks: ^2.13.1
    taze: ^19.9.2
    tsx: ^4.21.0
    typescript: ^5.9.3
  lint:
    '@octohash/eslint-config': ^0.2.4
    eslint: ^10.0.2
    lint-staged: ^16.3.0
  prod:
    '@clack/prompts': ^1.0.1
    ansis: ^4.2.0
    cac: ^7.0.0
    p-limit: ^7.3.0
    pathe: ^2.0.3
    rimraf: ^6.1.3
    tildify: ^3.0.0
    tinyglobby: ^0.2.15
  test:
    vitest: ^4.0.18
  types:
    '@types/node': ^25.3.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
